services:
  - type: web
    name: medical-chatbot-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
